### ISSUE TITLE
Add circuitBreaker for requests

### ISSUE THREAD

**Issue by tbille** [canonical-web-and-design/canonicalwebteam.http#11]
To be able to use this project in snapcraft.io or other sensitive projects we need to be able to support CircuitBreakers

You can check requests are treated in snapcraft.io: https://github.com/canonical-websites/snapcraft.io/blob/master/webapp/api/requests.py

**Comment by jpmartinspt** [comment]
@tbille @nottrobin Should the circuit breaker be configurable(maximum failures and reset time)?

**Comment by nottrobin** [comment]
@jpmartinspt I think the real question is- do we currently have a case where we want to configure it? Because if not I think we shouldn't complicate the interface.

I'm guessing that at the moment we probably want to start with the same settings in all sites. But we may want to configure the circuitbreaker for debug mode, like I've done for the timeouts in one or two sites. Maybe this argument is enough to say we should make it configurable? Or we could simply make this module itself behave differently if `DEBUG` is set? What do you think?

**Comment by jpmartinspt** [comment]
@nottrobin I would add a flag to control if we want a session with or without circuit-breaker. We could leave configuration for when we have a site that really needs something different from out chosen defaults.

**Comment by nottrobin** [comment]
@jpmartinspt yeah that's a nice compromise. Let's do that.
